[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor="#F63366"
backgroundColor="#F5F5F5"
secondaryBackgroundColor="#FFFFFF"
textColor="#262730"
font="sans serif"